modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"

[[mods]]
modId="aae_extra"
version="11.25.24"
displayName="AAE extra"
credits="mcreator"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="EngieGaems"
description="hmph"

[[dependencies.aae_extra]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




